import { Document, type FileChild, HeadingLevel, Packer, Paragraph, TextRun } from "docx"
import { jsPDF } from "jspdf"
import type { Doc } from "@/convex/_generated/dataModel"
import { downloadTextFile, slugifyRole } from "@/lib/tailored-export"

type AnalysisExport = {
  analysis: Doc<"analyses">
  resume?: Doc<"resumes"> | null
  jobPosting?: Doc<"jobPostings"> | null
}

function downloadBlob(filename: string, blob: Blob) {
  const url = URL.createObjectURL(blob)
  const a = document.createElement("a")
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

function metaLines({ analysis, resume, jobPosting }: AnalysisExport) {
  const title = jobPosting?.title ?? "Job match analysis"
  const date = new Date(analysis.createdAt).toLocaleString()
  return {
    title,
    date,
    resumeName: resume?.fileName ?? "—",
    fileSlug: slugifyRole(title) || "report",
  }
}

export function analysisToMarkdown({ analysis, resume, jobPosting }: AnalysisExport): string {
  const { title, date, resumeName } = metaLines({ analysis, resume, jobPosting })
  const lines: string[] = [
    `# JobFit AI — Match Report`,
    ``,
    `**Role:** ${title}`,
    `**Resume:** ${resumeName}`,
    `**Date:** ${date}`,
    `**Match score:** ${analysis.matchPercentage}%`,
    `**Seniority fit:** ${analysis.seniorityFit}`,
    ``,
    `## Matching skills`,
    ...analysis.matchingSkills.map((s) => `- ${s}`),
    ``,
    `## Missing skills`,
    ...analysis.missingSkills.map((s) => `- ${s}`),
  ]

  if (analysis.redFlags.length > 0) {
    lines.push(``, `## Red flags`, ...analysis.redFlags.map((f) => `- ${f}`))
  }

  if (analysis.skillCategories?.length) {
    lines.push(``, `## Skill categories`)
    for (const cat of analysis.skillCategories) {
      lines.push(`- **${cat.name}** (${cat.score}%): matched ${cat.matched.join(", ") || "—"}`)
    }
  }

  lines.push(``, `## Recommendations`, ...analysis.recommendations.map((r, i) => `${i + 1}. ${r}`))
  lines.push(``, `---`, `*Generated by JobFit AI*`)

  return lines.join("\n")
}

export function downloadAnalysisMarkdown(data: AnalysisExport) {
  const { fileSlug } = metaLines(data)
  downloadTextFile(`jobfit-report-${fileSlug}.md`, analysisToMarkdown(data))
}

export async function downloadAnalysisDocx(data: AnalysisExport): Promise<void> {
  const { analysis } = data
  const { title, date, resumeName, fileSlug } = metaLines(data)

  const children: FileChild[] = [
    new Paragraph({ text: "JobFit AI — Match Report", heading: HeadingLevel.HEADING_1 }),
    new Paragraph({
      children: [new TextRun({ text: "Role: ", bold: true }), new TextRun(title)],
    }),
    new Paragraph({
      children: [new TextRun({ text: "Resume: ", bold: true }), new TextRun(resumeName)],
    }),
    new Paragraph({
      children: [new TextRun({ text: "Date: ", bold: true }), new TextRun(date)],
    }),
    new Paragraph({
      children: [
        new TextRun({ text: "Match score: ", bold: true }),
        new TextRun(`${analysis.matchPercentage}%`),
      ],
    }),
    new Paragraph({
      children: [
        new TextRun({ text: "Seniority fit: ", bold: true }),
        new TextRun(analysis.seniorityFit),
      ],
    }),
    new Paragraph({ text: "" }),
    new Paragraph({ text: "Matching skills", heading: HeadingLevel.HEADING_2 }),
    ...analysis.matchingSkills.map((s) => new Paragraph({ text: `• ${s}` })),
    new Paragraph({ text: "" }),
    new Paragraph({ text: "Missing skills", heading: HeadingLevel.HEADING_2 }),
    ...analysis.missingSkills.map((s) => new Paragraph({ text: `• ${s}` })),
  ]

  if (analysis.redFlags.length > 0) {
    children.push(
      new Paragraph({ text: "" }),
      new Paragraph({ text: "Red flags", heading: HeadingLevel.HEADING_2 }),
      ...analysis.redFlags.map((f) => new Paragraph({ text: `• ${f}` })),
    )
  }

  if (analysis.skillCategories?.length) {
    children.push(
      new Paragraph({ text: "" }),
      new Paragraph({ text: "Skill categories", heading: HeadingLevel.HEADING_2 }),
    )
    for (const cat of analysis.skillCategories) {
      children.push(
        new Paragraph({
          children: [
            new TextRun({ text: `${cat.name} (${cat.score}%)`, bold: true }),
            new TextRun(` — matched ${cat.matched.join(", ") || "—"}`),
          ],
        }),
      )
    }
  }

  children.push(
    new Paragraph({ text: "" }),
    new Paragraph({ text: "Recommendations", heading: HeadingLevel.HEADING_2 }),
    ...analysis.recommendations.map(
      (r, i) =>
        new Paragraph({
          children: [new TextRun({ text: `${i + 1}. `, bold: true }), new TextRun(r)],
        }),
    ),
    new Paragraph({ text: "" }),
    new Paragraph({
      children: [new TextRun({ text: "Generated by JobFit AI", italics: true, size: 18 })],
    }),
  )

  const doc = new Document({ sections: [{ children }] })
  const blob = await Packer.toBlob(doc)
  downloadBlob(`jobfit-report-${fileSlug}.docx`, blob)
}

export function downloadAnalysisPdf(data: AnalysisExport) {
  const { analysis } = data
  const { title, date, resumeName, fileSlug } = metaLines(data)
  const doc = new jsPDF({ unit: "pt", format: "a4" })
  const margin = 48
  const maxWidth = doc.internal.pageSize.getWidth() - margin * 2
  let y = margin

  const ensureSpace = (needed: number) => {
    if (y + needed > doc.internal.pageSize.getHeight() - margin) {
      doc.addPage()
      y = margin
    }
  }

  const write = (
    text: string,
    opts?: { bold?: boolean; size?: number; color?: [number, number, number] },
  ) => {
    doc.setFont("helvetica", opts?.bold ? "bold" : "normal")
    doc.setFontSize(opts?.size ?? 11)
    if (opts?.color) doc.setTextColor(...opts.color)
    else doc.setTextColor(30, 30, 30)
    const lines = doc.splitTextToSize(text, maxWidth) as string[]
    ensureSpace(lines.length * ((opts?.size ?? 11) + 4) + 4)
    doc.text(lines, margin, y)
    y += lines.length * ((opts?.size ?? 11) + 4) + 6
  }

  const section = (heading: string, items: string[]) => {
    write(heading, { bold: true, size: 13 })
    if (items.length === 0) {
      write("—", { color: [120, 120, 120] })
    } else {
      for (const item of items) write(`• ${item}`)
    }
    y += 6
  }

  write("JobFit AI — Match Report", { bold: true, size: 18 })
  write(`Role: ${title}`, { size: 12 })
  write(`Resume: ${resumeName}`, { size: 10, color: [90, 90, 90] })
  write(`Date: ${date}`, { size: 10, color: [90, 90, 90] })
  write(`Match score: ${analysis.matchPercentage}%  ·  Seniority: ${analysis.seniorityFit}`, {
    bold: true,
    size: 12,
  })
  y += 8

  section("Matching skills", analysis.matchingSkills)
  section("Missing skills", analysis.missingSkills)
  if (analysis.redFlags.length > 0) section("Red flags", analysis.redFlags)

  if (analysis.skillCategories?.length) {
    write("Skill categories", { bold: true, size: 13 })
    for (const cat of analysis.skillCategories) {
      write(`${cat.name} (${cat.score}%): matched ${cat.matched.join(", ") || "—"}`, { size: 10 })
    }
    y += 6
  }

  write("Recommendations", { bold: true, size: 13 })
  for (const [i, r] of analysis.recommendations.entries()) {
    write(`${i + 1}. ${r}`)
  }
  y += 8
  write("Generated by JobFit AI", { size: 9, color: [140, 140, 140] })

  doc.save(`jobfit-report-${fileSlug}.pdf`)
}
