import type { Doc } from "@/convex/_generated/dataModel"

type AnalysisExport = {
  analysis: Doc<"analyses">
  resume?: Doc<"resumes"> | null
  jobPosting?: Doc<"jobPostings"> | null
}

export function analysisToMarkdown({ analysis, resume, jobPosting }: AnalysisExport): string {
  const title = jobPosting?.title ?? "Job match analysis"
  const date = new Date(analysis.createdAt).toLocaleString()
  const lines: string[] = [
    `# JobFit AI — Match Report`,
    ``,
    `**Role:** ${title}`,
    `**Resume:** ${resume?.fileName ?? "—"}`,
    `**Date:** ${date}`,
    `**Match score:** ${analysis.matchPercentage}%`,
    `**Seniority fit:** ${analysis.seniorityFit}`,
    ``,
    `## Matching skills`,
    ...analysis.matchingSkills.map((s) => `- ${s}`),
    ``,
    `## Missing skills`,
    ...analysis.missingSkills.map((s) => `- ${s}`),
  ]

  if (analysis.redFlags.length > 0) {
    lines.push(``, `## Red flags`, ...analysis.redFlags.map((f) => `- ${f}`))
  }

  if (analysis.skillCategories?.length) {
    lines.push(``, `## Skill categories`)
    for (const cat of analysis.skillCategories) {
      lines.push(`- **${cat.name}** (${cat.score}%): matched ${cat.matched.join(", ") || "—"}`)
    }
  }

  lines.push(``, `## Recommendations`, ...analysis.recommendations.map((r, i) => `${i + 1}. ${r}`))
  lines.push(``, `---`, `*Generated by JobFit AI*`)

  return lines.join("\n")
}
