type Bullet = { original: string; rewritten: string; rationale?: string }

/** Markdown pack of rewritten bullets for pasting into a CV. */
export function tailoredBulletsToMarkdown(
  bullets: Bullet[],
  meta?: { jobTitle?: string; generatedAt?: Date },
): string {
  const title = meta?.jobTitle?.trim() || "Target role"
  const when = (meta?.generatedAt ?? new Date()).toISOString().slice(0, 10)
  const lines = [
    `# Tailored resume bullets`,
    ``,
    `**Role:** ${title}`,
    `**Generated:** ${when}`,
    ``,
    `Copy the **After** lines into your resume. Verify employers, dates, and metrics before sending.`,
    ``,
  ]

  bullets.forEach((b, i) => {
    lines.push(
      `## Bullet ${i + 1}`,
      ``,
      `### After`,
      ``,
      b.rewritten,
      ``,
      `### Before`,
      ``,
      b.original,
    )
    if (b.rationale?.trim()) {
      lines.push(``, `### Why`, ``, b.rationale.trim())
    }
    lines.push(``)
  })

  lines.push(`---`, `*Generated by JobFit AI*`)
  return lines.join("\n")
}

export function tailoredBulletsPlainList(bullets: Bullet[]): string {
  return bullets
    .map((b) => b.rewritten.trim())
    .filter(Boolean)
    .map((line) => (line.startsWith("•") || line.startsWith("-") ? line : `• ${line}`))
    .join("\n")
}

export function downloadTextFile(filename: string, content: string, mime = "text/markdown") {
  const blob = new Blob([content], { type: `${mime};charset=utf-8` })
  const url = URL.createObjectURL(blob)
  const a = document.createElement("a")
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}
