import { Document, type FileChild, HeadingLevel, Packer, Paragraph, TextRun } from "docx"
import { jsPDF } from "jspdf"

type Bullet = { original: string; rewritten: string; rationale?: string }

/** Markdown pack of rewritten bullets for pasting into a CV. */
export function tailoredBulletsToMarkdown(
  bullets: Bullet[],
  meta?: { jobTitle?: string; generatedAt?: Date },
): string {
  const title = meta?.jobTitle?.trim() || "Target role"
  const when = (meta?.generatedAt ?? new Date()).toISOString().slice(0, 10)
  const lines = [
    `# Tailored resume bullets`,
    ``,
    `**Role:** ${title}`,
    `**Generated:** ${when}`,
    ``,
    `Copy the **After** lines into your resume. Verify employers, dates, and metrics before sending.`,
    ``,
  ]

  bullets.forEach((b, i) => {
    lines.push(
      `## Bullet ${i + 1}`,
      ``,
      `### After`,
      ``,
      b.rewritten,
      ``,
      `### Before`,
      ``,
      b.original,
    )
    if (b.rationale?.trim()) {
      lines.push(``, `### Why`, ``, b.rationale.trim())
    }
    lines.push(``)
  })

  lines.push(`---`, `*Generated by JobFit AI*`)
  return lines.join("\n")
}

export function tailoredBulletsPlainList(bullets: Bullet[]): string {
  return bullets
    .map((b) => b.rewritten.trim())
    .filter(Boolean)
    .map((line) => (line.startsWith("•") || line.startsWith("-") ? line : `• ${line}`))
    .join("\n")
}

export function downloadTextFile(filename: string, content: string, mime = "text/markdown") {
  const blob = new Blob([content], { type: `${mime};charset=utf-8` })
  const url = URL.createObjectURL(blob)
  const a = document.createElement("a")
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

function downloadBlob(filename: string, blob: Blob) {
  const url = URL.createObjectURL(blob)
  const a = document.createElement("a")
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

export function slugifyRole(jobTitle?: string) {
  return (jobTitle ?? "role")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 40)
}

export async function downloadTailoredDocx(
  bullets: Bullet[],
  meta?: { jobTitle?: string },
): Promise<void> {
  const title = meta?.jobTitle?.trim() || "Target role"
  const children: FileChild[] = [
    new Paragraph({
      text: "Tailored resume bullets",
      heading: HeadingLevel.HEADING_1,
    }),
    new Paragraph({
      children: [new TextRun({ text: "Role: ", bold: true }), new TextRun(title)],
    }),
    new Paragraph({
      children: [
        new TextRun({
          text: "Copy the After lines into your resume. Verify employers, dates, and metrics.",
          italics: true,
          size: 20,
        }),
      ],
    }),
    new Paragraph({ text: "" }),
  ]

  bullets.forEach((b, i) => {
    children.push(
      new Paragraph({
        text: `Bullet ${i + 1}`,
        heading: HeadingLevel.HEADING_2,
      }),
      new Paragraph({
        children: [new TextRun({ text: "After", bold: true, color: "15803D" })],
      }),
      new Paragraph({ text: b.rewritten }),
      new Paragraph({
        children: [new TextRun({ text: "Before", bold: true, color: "6B7280" })],
      }),
      new Paragraph({
        children: [new TextRun({ text: b.original, strike: true, color: "6B7280" })],
      }),
    )
    if (b.rationale?.trim()) {
      children.push(
        new Paragraph({
          children: [
            new TextRun({ text: "Why: ", italics: true }),
            new TextRun({ text: b.rationale.trim(), italics: true }),
          ],
        }),
      )
    }
    children.push(new Paragraph({ text: "" }))
  })

  children.push(
    new Paragraph({
      children: [new TextRun({ text: "Generated by JobFit AI", italics: true, size: 18 })],
    }),
  )

  const doc = new Document({
    sections: [{ children }],
  })
  const blob = await Packer.toBlob(doc)
  downloadBlob(`tailored-bullets-${slugifyRole(meta?.jobTitle) || "role"}.docx`, blob)
}

export function downloadTailoredPdf(bullets: Bullet[], meta?: { jobTitle?: string }) {
  const title = meta?.jobTitle?.trim() || "Target role"
  const doc = new jsPDF({ unit: "pt", format: "a4" })
  const margin = 48
  const maxWidth = doc.internal.pageSize.getWidth() - margin * 2
  let y = margin

  const ensureSpace = (needed: number) => {
    if (y + needed > doc.internal.pageSize.getHeight() - margin) {
      doc.addPage()
      y = margin
    }
  }

  const write = (
    text: string,
    opts?: { bold?: boolean; size?: number; color?: [number, number, number] },
  ) => {
    doc.setFont("helvetica", opts?.bold ? "bold" : "normal")
    doc.setFontSize(opts?.size ?? 11)
    if (opts?.color) doc.setTextColor(...opts.color)
    else doc.setTextColor(30, 30, 30)
    const lines = doc.splitTextToSize(text, maxWidth) as string[]
    ensureSpace(lines.length * ((opts?.size ?? 11) + 4) + 4)
    doc.text(lines, margin, y)
    y += lines.length * ((opts?.size ?? 11) + 4) + 6
  }

  write("Tailored resume bullets", { bold: true, size: 18 })
  write(`Role: ${title}`, { size: 12 })
  write("Copy the After lines into your resume. Verify employers, dates, and metrics.", {
    size: 10,
    color: [100, 100, 100],
  })
  y += 8

  bullets.forEach((b, i) => {
    write(`Bullet ${i + 1}`, { bold: true, size: 13 })
    write("After", { bold: true, size: 10, color: [21, 128, 61] })
    write(b.rewritten)
    write("Before", { bold: true, size: 10, color: [107, 114, 128] })
    write(b.original, { color: [107, 114, 128] })
    if (b.rationale?.trim()) {
      write(`Why: ${b.rationale.trim()}`, { size: 10, color: [90, 90, 90] })
    }
    y += 8
  })

  write("Generated by JobFit AI", { size: 9, color: [140, 140, 140] })
  doc.save(`tailored-bullets-${slugifyRole(meta?.jobTitle) || "role"}.pdf`)
}
